payload:
- DOMAIN-SUFFIX,4kdownload.com
- DOMAIN-SUFFIX,aihubmix.com
- DOMAIN-SUFFIX,bagevm.com
- DOMAIN-SUFFIX,bitsum.com
- DOMAIN-SUFFIX,boil.network
- DOMAIN-SUFFIX,caddyserver.com
- DOMAIN-SUFFIX,cryptomator.org
- DOMAIN-SUFFIX,debian.org
- DOMAIN-SUFFIX,dmit.io
- DOMAIN-SUFFIX,docker.com
- DOMAIN-SUFFIX,docker.io
- DOMAIN-SUFFIX,grafana.com
- DOMAIN-SUFFIX,home-assistant.io
- DOMAIN-SUFFIX,ixsystems.com
- DOMAIN-SUFFIX,krill-ai.com
- DOMAIN-SUFFIX,lencr.org
- DOMAIN-SUFFIX,letsencrypt.org
- DOMAIN-SUFFIX,linuxserver.io
- DOMAIN-SUFFIX,mesl.cloud
- DOMAIN-SUFFIX,misaka.io
- DOMAIN-SUFFIX,myqnap.org
- DOMAIN-SUFFIX,myqnapcloud.com
- DOMAIN-SUFFIX,myqnapcloud.io
- DOMAIN-SUFFIX,nabu.casa
- DOMAIN-SUFFIX,netlify.com
- DOMAIN-SUFFIX,nssurge.com
- DOMAIN-SUFFIX,openrouter.ai
- DOMAIN-SUFFIX,openwrt.org
- DOMAIN-SUFFIX,pfsense.org
- DOMAIN-SUFFIX,prometheus.io
- DOMAIN-SUFFIX,proxmox.com
- DOMAIN-SUFFIX,qnap.com
- DOMAIN-SUFFIX,railway.com
- DOMAIN-SUFFIX,realvnc.com
- DOMAIN-SUFFIX,revenuecat.com
- DOMAIN-SUFFIX,speedypage.com
- DOMAIN-SUFFIX,tailscale.com
- DOMAIN-SUFFIX,tailscale.io
- DOMAIN-SUFFIX,talkatone.com
- DOMAIN-SUFFIX,ticktick.com
- DOMAIN-SUFFIX,tktn.be
- DOMAIN-SUFFIX,traefik.io
- DOMAIN-SUFFIX,truenas.com
- DOMAIN-SUFFIX,tuta.com
- DOMAIN-SUFFIX,vnc.com
- DOMAIN-SUFFIX,vps.hosting
- DOMAIN-SUFFIX,y-too.com
- DOMAIN-SUFFIX,zeabur.com