payload:
- DOMAIN-SUFFIX,4kdownload.com
- DOMAIN-SUFFIX,aihubmix.com
- DOMAIN-SUFFIX,bitsum.com
- DOMAIN-SUFFIX,cryptomator.org
- DOMAIN-SUFFIX,ephone.ai
- DOMAIN-SUFFIX,gptuu.com
- DOMAIN-SUFFIX,iturrit.com
- DOMAIN-SUFFIX,lencr.org
- DOMAIN-SUFFIX,moleapi.com
- DOMAIN-SUFFIX,morsegpt.net
- DOMAIN-SUFFIX,myqnap.org
- DOMAIN-SUFFIX,myqnapcloud.com
- DOMAIN-SUFFIX,myqnapcloud.io
- DOMAIN-SUFFIX,netlify.com
- DOMAIN-SUFFIX,nssurge.com
- DOMAIN-SUFFIX,oaipro.com
- DOMAIN-SUFFIX,one.ooo.cool
- DOMAIN-SUFFIX,openrouter.ai
- DOMAIN-SUFFIX,qnap.com
- DOMAIN-SUFFIX,railway.com
- DOMAIN-SUFFIX,realvnc.com
- DOMAIN-SUFFIX,revenuecat.com
- DOMAIN-SUFFIX,tailscale.com
- DOMAIN-SUFFIX,tailscale.io
- DOMAIN-SUFFIX,talkatone.com
- DOMAIN-SUFFIX,theb.ai
- DOMAIN-SUFFIX,ticktick.com
- DOMAIN-SUFFIX,tktn.be
- DOMAIN-SUFFIX,tuta.com
- DOMAIN-SUFFIX,vnc.com